server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emergency
    username: root
    password: pass@word1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      properties:
        spring.json.type.mapping: event:com.ust.Incident_Management_System.Model.IncidentReport
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        # Map the JSON type to the IncidentReport class
#        spring.json.type.mapping: event:com.ust.Notification_service.IncidentReport
        # If you need to include type information in headers
        spring.json.add.type.headers: true
        # The default type for deserialization
#        spring.json.value.default.type: com.ust.Notification_service.IncidentReport

eureka:
  client:
    registerWithEureka: true        # Registers this service with the Eureka server
    fetchRegistry: true             # Fetches the registry from the Eureka server
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # URL of the Eureka server to connect with
  instance:
    hostname: localhost             # The hostname of the instance
    instance-id: "${spring.application.name}:${instanceId:${random.value}}"  # Instance ID, with dynamic values