eureka:
  client:
    register-with-eureka: false
server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: emergency-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/emergency/**
        - id: volunteer-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/volunteers/**
        - id: incident-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/incident/**